export const CITIES_BY_STATE: Record<string, string[]> = {
  'Abia': ['Aba', 'Umuahia', 'Ohafia', 'Arochukwu', 'Bende', 'Isuikwuato', 'Ukwa', 'Umunneochi'],
  'Adamawa': ['Yola', 'Mubi', 'Jimeta', 'Numan', 'Ganye', 'Michika', 'Song', 'Gombi'],
  'Akwa Ibom': ['Uyo', 'Eket', 'Ikot Ekpene', 'Abak', 'Oron', 'Etinan', 'Ikot Abasi', 'Itu'],
  'Anambra': ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia', 'Aguata', 'Ihiala', 'Ogidi', 'Oba', 'Obosi', 'Abagana'],
  'Bauchi': ['Bauchi', 'Azare', 'Misau', 'Katagum', 'Alkaleri', 'Gamawa', 'Dass', 'Toro'],
  'Bayelsa': ['Yenagoa', 'Brass', 'Sagbama', 'Ekeremor', 'Kolokuma', 'Nembe', 'Ogbia', 'Southern Ijaw'],
  'Benue': ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala', 'Vandeikya', 'Zaki Biam', 'Adikpo', 'Aliade'],
  'Borno': ['Maiduguri', 'Biu', 'Bama', 'Gwoza', 'Damboa', 'Konduga', 'Kukawa', 'Monguno'],
  'Cross River': ['Calabar', 'Ikom', 'Ogoja', 'Obudu', 'Ugep', 'Akamkpa', 'Bekwara', 'Obubra'],
  'Delta': ['Asaba', 'Warri', 'Sapele', 'Ughelli', 'Agbor', 'Abraka', 'Kwale', 'Oleh', 'Ozoro'],
  'Ebonyi': ['Abakaliki', 'Afikpo', 'Onueke', 'Ishielu', 'Ohaozara', 'Ivo', 'Ikwo', 'Ohaukwu'],
  'Edo': ['Benin City', 'Auchi', 'Uromi', 'Ekpoma', 'Igarra', 'Irrua', 'Igueben', 'Ubiaja'],
  'Ekiti': ['Ado-Ekiti', 'Ikere-Ekiti', 'Ilawe-Ekiti', 'Emure-Ekiti', 'Aramoko-Ekiti', 'Ise-Ekiti', 'Efon-Alaaye', 'Oye-Ekiti'],
  'Enugu': ['Enugu', 'Nsukka', 'Agbani', 'Awgu', 'Udi', 'Oji River', 'Nnaji', 'Igbo-Eze'],
  'FCT': ['Abuja', 'Gwagwalada', 'Kuje', 'Bwari', 'Kwali', 'Abaji', 'Lugbe', 'Nyanya', 'Kubwa', 'Gwarinpa'],
  'Gombe': ['Gombe', 'Dukku', 'Kaltungo', 'Billiri', 'Nafada', 'Balanga', 'Yamaltu', 'Funakaye'],
  'Imo': ['Owerri', 'Orlu', 'Okigwe', 'Oguta', 'Oru East', 'Ngor Okpala', 'Mbano', 'Mbaitoli'],
  'Jigawa': ['Dutse', 'Hadejia', 'Gumel', 'Birnin Kudu', 'Ringim', 'Kazaure', 'Kiyawa', 'Garki'],
  'Kaduna': ['Kaduna', 'Zaria', 'Kafanchan', 'Kachia', 'Lere', 'Soba', 'Birnin Gwari', 'Makarfi'],
  'Kano': ['Kano', 'Wudil', 'Gaya', 'Rano', 'Bichi', 'Doguwa', 'Kura', 'Nasarawa', 'Tofa', 'Shanono'],
  'Katsina': ['Katsina', 'Daura', 'Funtua', 'Malumfashi', 'Mani', 'Musawa', 'Jibia', 'Kaita'],
  'Kebbi': ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru', 'Kamba', 'Jega', 'Bagudo', 'Aliero'],
  'Kogi': ['Lokoja', 'Okene', 'Kabba', 'Idah', 'Isanlu', 'Ankpa', 'Ajaokuta', 'Dekina'],
  'Kwara': ['Ilorin', 'Offa', 'Omu-Aran', 'Jebba', 'Lafiagi', 'Kaiama', 'Pategi', 'Share'],
  'Lagos': ['Lagos Island', 'Lagos Mainland', 'Ikeja', 'Surulere', 'Oshodi', 'Alimosho', 'Agege', 'Mushin', 'Apapa', 'Yaba', 'Victoria Island', 'Lekki', 'Ajah', 'Ikorodu', 'Epe', 'Badagry', 'Ojodu', 'Iyana Ipaja', 'Ojo', 'Ajeromi-Ifelodun'],
  'Nasarawa': ['Lafia', 'Keffi', 'Akwanga', 'Nassarawa-Eggon', 'Doma', 'Toto', 'Wamba', 'Awe'],
  'Niger': ['Minna', 'Bida', 'Suleja', 'Kontagora', 'Lapai', 'Agaie', 'Mokwa', 'New Bussa'],
  'Ogun': ['Abeokuta', 'Sagamu', 'Ijebu-Ode', 'Ilaro', 'Ota', 'Ifo', 'Shagamu', 'Ijebu-Igbo', 'Mowe', 'Sango-Ota'],
  'Ondo': ['Akure', 'Ondo', 'Owo', 'Okitipupa', 'Ikare', 'Irele', 'Idanre', 'Ile-Oluji'],
  'Osun': ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede', 'Iwo', 'Ikirun', 'Ejigbo', 'Gbongan'],
  'Oyo': ['Ibadan', 'Ogbomosho', 'Oyo', 'Iseyin', 'Saki', 'Eruwa', 'Igbo-Ora', 'Lalupon', 'Fiditi', 'Moniya'],
  'Plateau': ['Jos', 'Bukuru', 'Shendam', 'Pankshin', 'Langtang', 'Wase', 'Mikang', 'Bassa'],
  'Rivers': ['Port Harcourt', 'Obio-Akpor', 'Eleme', 'Okrika', 'Bonny', 'Degema', 'Ahoada', 'Ogba-Egbema', 'Abua', 'Khana'],
  'Sokoto': ['Sokoto', 'Bodinga', 'Dange-Shuni', 'Gada', 'Goronyo', 'Gudu', 'Gwadabawa', 'Illela'],
  'Taraba': ['Jalingo', 'Wukari', 'Bali', 'Gashaka', 'Gembu', 'Ibi', 'Karim-Lamido', 'Kurmi'],
  'Yobe': ['Damaturu', 'Potiskum', 'Gashua', 'Nguru', 'Geidam', 'Jakusko', 'Bade', 'Bursari'],
  'Zamfara': ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Anka', 'Bakura', 'Birnin Magaji', 'Bungudu', 'Maradun'],
}
